library(plyr)
library(dplyr)
library(stringr)
library(ggplot2)
raw <- read.csv("./MDC/visit-by-hr.csv")
raw <- raw[-c(1),2:3]
names(raw) <- c("Day","Visits")
raw$Day <- gsub("/2014","X",raw$Day)
raw$Day <- gsub("/2015","X",raw$Day)
raw$Visits <- as.numeric( sub(",", "", raw$Visits) )
raw <- mutate(raw,Hour=str_sub(raw$Day,start=-5))
time <- raw %>% group_by(Hour) %>% summarise(sum(Visits))
names(time) <- c("Hour","Visits")
ggplot(data=time, aes(x=Hour, y=Visits)) + geom_bar(stat="identity")